services:
  - type: web
    name: medical-ai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false