services:
  - type: web
    name: medical-ai-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && gunicorn api:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false